version: "3"
services:
  app:
    build: .
    image: app
    ports:
      - "8081:8080"
    networks:
      - net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=pdf
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:

networks:
  net:
